export const DRAFT_PHOTOS = {
  2025: [
    { file: 'foto1.jpg', caption: 'Os GMs reunidos ao final do Draft' },
    { file: 'foto2.jpg', caption: 'Preparativos' },
    { file: 'foto3.jpg', caption: 'Campeão de 2024 e Unicornio' },
    { file: 'foto4.jpg', caption: 'O cobiçado troféu' },
    { file: 'foto5.jpg', caption: 'A competição pelas Picks' },
    { file: 'foto6.jpg', caption: 'A magia do Draft' },
    { file: 'foto7.jpg', caption: 'Pausa para descansar' },
    { file: 'foto8.jpg', caption: 'Draft finalizado com sucesso' },
  ],
  2024: [
    { file: 'foto1.jpg', caption: 'Foco na apresentação do comissário' },
    { file: 'foto2.jpg', caption: 'A passagem do unicórnio' },
    { file: 'foto3.jpg', caption: 'Novo Unicornio' },
    { file: 'foto4.jpg', caption: 'O campeão de 2023' },
    { file: 'foto5.jpg', caption: 'Vice de novo' },
    { file: 'foto6.jpg', caption: 'A competição pelas picks' },
    { file: 'foto7.jpg', caption: 'Hora das escolhas' },
    { file: 'foto8.jpg', caption: 'Draft finalizado com sucesso' },
  ],
  2023: [
    { file: 'foto1.jpg', caption: 'Os GMs reunidos ao final do Draft' },
    { file: 'foto2.jpg', caption: 'Inicio da Premiação' },
    { file: 'foto3.jpg', caption: 'Campeão 2014 e 2021' },
    { file: 'foto4.jpg', caption: 'Campeão 2015 e 2022' },
    { file: 'foto5.jpg', caption: 'Campeão 2016' },
    { file: 'foto6.jpg', caption: 'Unicórnio' },
    { file: 'foto7.jpg', caption: 'Hora das escolhas' },
    { file: 'foto8.jpg', caption: 'Início do churras' },
    { file: 'foto9.jpg', caption: 'GM e assador' },
    { file: 'foto10.jpg', caption: 'Choppinho bom' },
    { file: 'foto11.jpg', caption: 'Howmuch?' },
    { file: 'foto12.jpg', caption: 'Magia do Draft' },
  ],
  // adicione mais anos aqui
}